### ISSUE TITLE
Possibly unable to mount NFS on build 4210

### ISSUE THREAD

**Issue by SapphireExile** [llamasoft/RootMyRoku#1]
Unable to verify if this is a communication problem, or if build 4210 is incapable of mounting NFS. 

Device information: 
Model: C232X
Hisense Model: 58R6+
Software ver: 9.4.0 4210-94

**Comment by SapphireExile** [comment]
Manifest mount point has been tested with nfs.rootmyroku, local server-local IP, and local server- remote IP + forwarding, same result across all 3. Mountd forced to 33333, 111 and 2029 forwarded, firewall allowing, but my servers are old and stupid so could be a configuration problem.

**Comment by ammaraskar** [comment]
Aah sadly 4210 patches out the NFS mount feature.
