### ISSUE TITLE
Update occurred after jailbreak

### ISSUE THREAD

**Issue by agg23** [llamasoft/RootMyRoku#11]
I wanted to warn future users that the DNS change does not appear to be sufficient to blocking updates. My previously rooted TV updated to 10.5 right after I connected the device to the network and started to poke around in the OS through telnet.

This may _not_ be a fault of this jailbreak, and instead due to the update check that is required when enabling dev mode (see #10), but it seems unlikely that it would check and download the update, but not actually instigate it until 20 days alter.

@llamasoft, what hosts are you blocking via `dns.rootmyroku.com`? I imagine those should be blackholed in the `hosts` file or similar instead (it would also be nice if the update script could be identified and disabled).

**Comment by llamasoft** [comment]
It blocks pretty much _all_ of them: https://github.com/llamasoft/RootMyRoku/blob/main/server/setup.sh#L107-L114

Unfortunately, I've noticed that the DNS blocking at the device level isn't 100% perfect.  The primary issue is that `/etc/resolv.conf` is a symlink that points to `/tmp/resolv.conf` which is a world writable temp directory.  The startup script changes the `resolv.conf` file to use the blocking DNS server, but if your network connection status changes (e.g. network blip, restart WiFi, etc) then the `resolv.conf` file gets reset to the default DNS servers from your router's DHCP config.  The DNS blocker runs in a loop every 5-15 minutes, but that may potentially leave you exposed for a time.

Your best bet is to update the default DNS servers on your router as a failsafe.  If you don't trust using `dns.rootmyroku.com` for your whole network, I'd suggest setting up a Pi-Hole and blocking the appropriate domains.

For the time being, I've updated the `resolv.sh` script to monitor the config file more closely and reset any changes within a few seconds.  This should hopefully prevent accidental updates.  Apologies for not noticing this issue sooner.  Roku inadvertently helped me by banning my devices which prevents them from receiving updates even when DNS filtering fails.
