### ISSUE TITLE
Bypass Lets get started Screen

### ISSUE THREAD

**Issue by benmprojects** [llamasoft/RootMyRoku#15]
Hi,

I have manged to find a old 3 gen device thast has not been setup. If I complete the setup this will autoupdate blocking this root method. 

Is there anyway to bypass this screen?

Thanks

**Comment by llamasoft** [comment]
Nope, not that I know of.  The activation process has a mandatory update check before you're even given the option to login and you have to be logged in before you can enable developer mode. ☹️

**Comment by mightymos** [comment]
I have a model 2050X version 3.1 build 1198 and can confirm it allows entering developer mode following factory reset even at setup menu. I'm then able to upload dev-channel and hear a beep from the Roku. Unfortunately putty does seem to connect to telnet port. There was also apparently no telnet access enabled prior to factory reset (though dev-channel uploaded with beep).

I know this is not immediately helpful to the original poster but fyi.
